### PR TITLE
Accesors

### PR DESCRIPTION
**Pull request by ericaddison**
A few things here:
- Added accessor methods to `FilterBankStep` to set `nBands` and the filter window length. Currently fixed window type of `HannWindow` (which is fine...)
- Consolidated the `***ByteBufferizerStep` classes with their `Adaptive***` counterparts to match the `HuffmanEncoderStep` setup, i.e. set whether the `***ByteBufferizerStep` is adaptive or not either through a constructor or through a setter.
- Added a new `InputOutputStep` to take care of the file loading and writing. This was the obvious place to put an access method for setting the length of the signal window.
- Tried to update relevant calls in `FullAudioCompressor`. @JoshMusick you should check me on that.

### CODE REVIEW

**Comment by JoshMusick** [comment]
Hmm, this will not quite work as I see it.  If the Byte Bufferizers can have their adaptive capability toggled, then I would only create one instance of the line and subband byte bufferizers, and just use their accessor.  Secondly, with the addition of another step at the beginning of the pipeline, there are some indices that were used that will not work quite right. 

I will check out this branch and make necessary updates.

**Comment by ericaddison** [comment]
Ah, I was not sure if you'd want to toggle the adaptive-ness or still create separate instances, so I didn't change that choice... If it's too much work to change we can back-pedal!

**Comment by JoshMusick** [comment]
No worries, it's not a big deal to correct.

**Comment by JoshMusick** [comment]
I've pushed a commit with the necessary changes.  Merge it in if you think it's good to go!

**Comment by ericaddison** [comment]
looks good to me, merging!

**Pull request merged**
